spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm.admin-user:
  id: demo
  password: demo
  
server:
  servlet:
    context-path: /fintech/order-source/
  port: 80
  tomcat: 
    accesslog:
      pattern: '%h %l %u %t "%r" %s %b "%{Referer}i" "%{User-Agent}i" "%{X-Forwarded-For}i"' 
      directory: '${ACCESS_LOG:/tmp/access}'
      enabled: true
      rotate: false

logging:
  pattern:
    console: '[%date{ISO8601}] [${spring.application.name}] logLevel=%level pid=${PID:-} thread=%thread class=%logger{40} message="%msg"%n'
  level:
    com.babcock.accounts: DEBUG
  file:
    path: /tmp/log/accounts.log
swagger:
  base:
    package: com.fintech.ordersource.controller
    
spring:
  application:
    name: APPLICATION=ORDER-SOURCE DEV
    
# Kafka
  kafka:
    properties:
      sasl.mechanism: PLAIN
      bootstrap.servers: pkc-epwny.eastus.azure.confluent.cloud:9092
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule   required username='VOQHCPO6GYJZJGZ2'   password='o4mzip9b2/KeOu/DUIJDXUFObB9O5XLrcjE+m9y8ZHUN/ih6Vk5Oyzuc7AtgBwbE';
      security.protocol: SASL_SSL
      #spring.json.trusted.packages: *
      consumer: 
        #group-id: test_group
        enable-auto-commit: false
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      producer: 
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer